// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import "github.com/gqcn/platform/backend/internal/dao/internal"

// internalSpecsDao is internal type for wrapping internal DAO implements.
type internalSpecsDao = *internal.SpecsDao

// specsDao is the data access object for the table specs.
type specsDao struct {
	internalSpecsDao
}

// Specs is globally public accessible object for table specs operations.
var Specs = specsDao{
	internal.NewSpecsDao(),
}
