// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import "github.com/gqcn/platform/backend/internal/dao/internal"

// internalInstancesDao is internal type for wrapping internal DAO implements.
type internalInstancesDao = *internal.InstancesDao

// instancesDao is the data access object for the table instances.
type instancesDao struct {
	internalInstancesDao
}

// Instances is globally public accessible object for table instances operations.
var Instances = instancesDao{
	internal.NewInstancesDao(),
}
