// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import "github.com/gqcn/platform/backend/internal/dao/internal"

// internalUsersDao is internal type for wrapping internal DAO implements.
type internalUsersDao = *internal.UsersDao

// usersDao is the data access object for the table users.
// You can define custom methods on it to extend its functionality as you wish.
type usersDao struct {
	internalUsersDao
}

// Users is globally public accessible object for table users operations.
var Users = usersDao{
	internal.NewUsersDao(),
}
